# -*- coding: utf-8 -*-
"""Emotion novelty.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kv2lNZOwmcSQke4tfzCHv-mImwLS0yto

# PHASE 0 — COLAB SETUP
"""

import torch

print("GPU Available:", torch.cuda.is_available())
print("GPU Name:", torch.cuda.get_device_name(0))
print("CUDA Version:", torch.version.cuda)

!pip install -q transformers==4.36.2
!pip install -q datasets
!pip install -q torchaudio
!pip install -q accelerate
!pip install -q scikit-learn

from google.colab import drive
drive.mount('/content/drive')

import random
import numpy as np
import torch

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(42)

from torch.cuda.amp import GradScaler

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
scaler = GradScaler()

print("Using device:", device)

torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False

import os
os.listdir("/content/drive/MyDrive/sentinel dataset")

"""# PHASE 1 — Data Pipeline (Optimized for 16k × 8 sec)"""

import os
import torch
import torchaudio
import numpy as np
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from transformers import Wav2Vec2Processor

DATASET_PATH = "/content/drive/MyDrive/sentinel dataset"

paths = []
labels = []

for language in os.listdir(DATASET_PATH):
    lang_path = os.path.join(DATASET_PATH, language)
    if not os.path.isdir(lang_path):
        continue

    for label_name in ["normal", "abnormal"]:
        label_path = os.path.join(lang_path, label_name)
        if not os.path.isdir(label_path):
            continue

        for file in os.listdir(label_path):
            if file.endswith(".wav"):
                paths.append(os.path.join(label_path, file))
                labels.append(0 if label_name == "normal" else 1)

print("Total samples:", len(paths))

train_paths, val_paths, train_labels, val_labels = train_test_split(
    paths,
    labels,
    test_size=0.2,
    stratify=labels,
    random_state=42
)

print("Train size:", len(train_paths))
print("Val size:", len(val_paths))

TARGET_SR = 16000
MAX_LENGTH = 128000  # 8 sec

processor = Wav2Vec2Processor.from_pretrained(
    "facebook/wav2vec2-base"
)

class SentinelDataset(Dataset):
    def __init__(self, paths, labels):
        self.paths = paths
        self.labels = labels

    def __len__(self):
        return len(self.paths)

    def __getitem__(self, idx):
        path = self.paths[idx]
        label = self.labels[idx]

        waveform, sr = torchaudio.load(path)

        # Convert to mono
        if waveform.shape[0] > 1:
            waveform = torch.mean(waveform, dim=0, keepdim=True)

        # Resample if needed
        if sr != TARGET_SR:
            resampler = torchaudio.transforms.Resample(sr, TARGET_SR)
            waveform = resampler(waveform)

        waveform = waveform.squeeze()

        # Pad / Trim to 8 sec
        if len(waveform) > MAX_LENGTH:
            waveform = waveform[:MAX_LENGTH]
        else:
            padding = MAX_LENGTH - len(waveform)
            waveform = torch.nn.functional.pad(waveform, (0, padding))

        inputs = processor(
            waveform,
            sampling_rate=TARGET_SR,
            return_tensors="pt",
            padding="max_length",
            max_length=MAX_LENGTH,
            truncation=True,
            return_attention_mask=True
        )

        return {
            "input_values": inputs["input_values"].squeeze(0),
            "attention_mask": inputs["attention_mask"].squeeze(0),
            "label": torch.tensor(label, dtype=torch.long)
        }

BATCH_SIZE = 4

train_dataset = SentinelDataset(train_paths, train_labels)
val_dataset = SentinelDataset(val_paths, val_labels)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

batch = next(iter(train_loader))

print("Input shape:", batch["input_values"].shape)
print("Mask shape:", batch["attention_mask"].shape)
print("Labels shape:", batch["label"].shape)

"""# PHASE 2 — Baseline Training (Ablation Step 1)"""

import torch.nn as nn
from transformers import Wav2Vec2Model

class Wav2Vec2Baseline(nn.Module):
    def __init__(self, num_classes=2, freeze_feature_extractor=True):
        super().__init__()

        self.wav2vec = Wav2Vec2Model.from_pretrained(
            "facebook/wav2vec2-base"
        )

        if freeze_feature_extractor:
            for param in self.wav2vec.feature_extractor.parameters():
                param.requires_grad = False

        hidden_size = self.wav2vec.config.hidden_size

        self.classifier = nn.Sequential(
            nn.Linear(hidden_size, 256),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )

    def forward(self, input_values, attention_mask=None):

        outputs = self.wav2vec(
            input_values=input_values,
            attention_mask=attention_mask
        )

        x = outputs.last_hidden_state  # (B, T, H)

        x = torch.mean(x, dim=1)  # Mean pooling

        logits = self.classifier(x)

        return logits

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = Wav2Vec2Baseline().to(device)

print("Model loaded on:", device)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=2e-5,
    weight_decay=1e-4
)

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer,
    T_max=10
)

from sklearn.metrics import accuracy_score, recall_score, roc_auc_score
from tqdm import tqdm
import torch.nn.functional as F

def train_baseline(model, loader, optimizer, criterion):
    model.train()
    total_loss = 0

    all_preds = []
    all_labels = []
    all_probs = []

    for batch in tqdm(loader):
        input_values = batch["input_values"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["label"].to(device)

        optimizer.zero_grad()

        logits = model(input_values, attention_mask)

        loss = criterion(logits, labels)
        loss.backward()

        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()

        total_loss += loss.item()

        probs = F.softmax(logits, dim=1)[:, 1]
        preds = torch.argmax(logits, dim=1)

        all_preds.extend(preds.detach().cpu().numpy())
        all_labels.extend(labels.detach().cpu().numpy())
        all_probs.extend(probs.detach().cpu().numpy())

    acc = accuracy_score(all_labels, all_preds)
    recall_abnormal = recall_score(all_labels, all_preds, pos_label=1)
    roc = roc_auc_score(all_labels, all_probs)

    return total_loss / len(loader), acc, recall_abnormal, roc

def validate_baseline(model, loader, criterion):
    model.eval()
    total_loss = 0

    all_preds = []
    all_labels = []
    all_probs = []

    with torch.no_grad():
        for batch in tqdm(loader):
            input_values = batch["input_values"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["label"].to(device)

            logits = model(input_values, attention_mask)

            loss = criterion(logits, labels)
            total_loss += loss.item()

            probs = F.softmax(logits, dim=1)[:, 1]
            preds = torch.argmax(logits, dim=1)

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
            all_probs.extend(probs.cpu().numpy())

    acc = accuracy_score(all_labels, all_preds)
    recall_abnormal = recall_score(all_labels, all_preds, pos_label=1)
    roc = roc_auc_score(all_labels, all_probs)

    return total_loss / len(loader), acc, recall_abnormal, roc

optimizer = torch.optim.AdamW([
    {"params": model.wav2vec.parameters(), "lr": 1e-5},
    {"params": model.classifier.parameters(), "lr": 1e-4}
], weight_decay=1e-4)

for name, param in model.wav2vec.named_parameters():
    if "encoder.layers" in name:
        layer_num = int(name.split("encoder.layers.")[1].split(".")[0])
        if layer_num >= 8:  # last 4 layers (base has 12)
            param.requires_grad = True
        else:
            param.requires_grad = False

import numpy as np
print("Normal:", np.sum(np.array(train_labels)==0))
print("Abnormal:", np.sum(np.array(train_labels)==1))

model = Wav2Vec2Baseline().to(device)

for name, param in model.wav2vec.named_parameters():
    if "encoder.layers" in name:
        layer_num = int(name.split("encoder.layers.")[1].split(".")[0])
        if layer_num >= 8:  # last 4 layers
            param.requires_grad = True
        else:
            param.requires_grad = False

optimizer = torch.optim.AdamW([
    {"params": model.wav2vec.parameters(), "lr": 1e-5},
    {"params": model.classifier.parameters(), "lr": 1e-4}
], weight_decay=1e-4)

num_epochs = 3
best_roc = 0

for epoch in range(num_epochs):

    print(f"\nEpoch {epoch+1}/{num_epochs}")

    train_loss, train_acc, train_recall, train_roc = train_baseline(
        model, train_loader, optimizer, criterion
    )

    val_loss, val_acc, val_recall, val_roc = validate_baseline(
        model, val_loader, criterion
    )

    scheduler.step()

    print(f"Train Acc: {train_acc:.4f} | Recall: {train_recall:.4f} | ROC: {train_roc:.4f}")
    print(f"Val   Acc: {val_acc:.4f} | Recall: {val_recall:.4f} | ROC: {val_roc:.4f}")

    if val_roc > best_roc:
        best_roc = val_roc
        torch.save(model.state_dict(), "/content/drive/MyDrive/baseline_best.pt")
        print("Baseline best model saved!")

"""# PHASE 3 — Temporal Modeling Upgrade"""

import torch
import torch.nn as nn
from transformers import Wav2Vec2Model

class Wav2Vec2_BiLSTM_Attention(nn.Module):
    def __init__(self, num_classes=2):
        super().__init__()

        self.wav2vec = Wav2Vec2Model.from_pretrained(
            "facebook/wav2vec2-base"
        )

        hidden_size = self.wav2vec.config.hidden_size

        # BiLSTM
        self.bilstm = nn.LSTM(
            input_size=hidden_size,
            hidden_size=256,
            num_layers=2,
            batch_first=True,
            bidirectional=True,
            dropout=0.3
        )

        self.lstm_output_dim = 256 * 2

        # Attention Pooling
        self.attention = nn.Sequential(
            nn.Linear(self.lstm_output_dim, 128),
            nn.Tanh(),
            nn.Linear(128, 1)
        )

        self.classifier = nn.Sequential(
            nn.Linear(self.lstm_output_dim, 256),
            nn.ReLU(),
            nn.Dropout(0.4),
            nn.Linear(256, num_classes)
        )

    def forward(self, input_values, attention_mask=None):

        outputs = self.wav2vec(
            input_values=input_values,
            attention_mask=attention_mask
        )

        x = outputs.last_hidden_state  # (B, T, H)

        x, _ = self.bilstm(x)  # (B, T, 512)

        # Attention weights
        attn_scores = self.attention(x)  # (B, T, 1)
        attn_weights = torch.softmax(attn_scores, dim=1)

        # Weighted sum
        x = torch.sum(attn_weights * x, dim=1)

        logits = self.classifier(x)

        return logits

model = Wav2Vec2_BiLSTM_Attention().to(device)

for name, param in model.wav2vec.named_parameters():
    if "encoder.layers" in name:
        layer_num = int(name.split("encoder.layers.")[1].split(".")[0])
        if layer_num >= 8:
            param.requires_grad = True
        else:
            param.requires_grad = False

optimizer = torch.optim.AdamW([
    {"params": model.wav2vec.parameters(), "lr": 1e-5},
    {"params": model.bilstm.parameters(), "lr": 3e-4},
    {"params": model.attention.parameters(), "lr": 3e-4},
    {"params": model.classifier.parameters(), "lr": 3e-4},
], weight_decay=1e-4)

criterion = nn.CrossEntropyLoss()

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer,
    T_max=8
)

num_epochs = 5
best_roc = 0

for epoch in range(num_epochs):

    print(f"\nEpoch {epoch+1}/{num_epochs}")

    train_loss, train_acc, train_recall, train_roc = train_baseline(
        model, train_loader, optimizer, criterion
    )

    val_loss, val_acc, val_recall, val_roc = validate_baseline(
        model, val_loader, criterion
    )

    scheduler.step()

    print(f"Train Acc: {train_acc:.4f} | Recall: {train_recall:.4f} | ROC: {train_roc:.4f}")
    print(f"Val   Acc: {val_acc:.4f} | Recall: {val_recall:.4f} | ROC: {val_roc:.4f}")

    if val_roc > best_roc:
        best_roc = val_roc
        torch.save(model.state_dict(), "/content/drive/MyDrive/phase3_best.pt")
        print("Baseline best model saved!")

"""# Phase 4-Full SDED-T Architecture (without safety loss yet)."""

class SDED_T(nn.Module):
    def __init__(self, num_classes=2):
        super().__init__()

        self.wav2vec = Wav2Vec2Model.from_pretrained(
            "facebook/wav2vec2-base"
        )

        hidden_size = self.wav2vec.config.hidden_size

        # BiLSTM
        self.bilstm = nn.LSTM(
            input_size=hidden_size,
            hidden_size=256,
            num_layers=2,
            batch_first=True,
            bidirectional=True,
            dropout=0.3
        )

        self.lstm_output_dim = 256 * 2

        # Attention Pooling
        self.attention = nn.Sequential(
            nn.Linear(self.lstm_output_dim, 128),
            nn.Tanh(),
            nn.Linear(128, 1)
        )

        # Shared representation
        self.shared = nn.Sequential(
            nn.Linear(self.lstm_output_dim, 256),
            nn.ReLU(),
            nn.Dropout(0.4)
        )

        # Main emotion head
        self.emotion_head = nn.Linear(256, num_classes)

        # Drift head
        self.drift_head = nn.Linear(256, 1)

        # Confidence head
        self.confidence_head = nn.Sequential(
            nn.Linear(256, 64),
            nn.ReLU(),
            nn.Linear(64, 1),
            nn.Sigmoid()
        )

    def forward(self, input_values, attention_mask=None):

        outputs = self.wav2vec(
            input_values=input_values,
            attention_mask=attention_mask
        )

        x = outputs.last_hidden_state

        x, _ = self.bilstm(x)

        attn_scores = self.attention(x)
        attn_weights = torch.softmax(attn_scores, dim=1)
        x = torch.sum(attn_weights * x, dim=1)

        shared = self.shared(x)

        emotion_logits = self.emotion_head(shared)
        drift_score = self.drift_head(shared)
        confidence_score = self.confidence_head(shared)

        return {
            "emotion_logits": emotion_logits,
            "drift_score": drift_score,
            "confidence_score": confidence_score
        }

model = SDED_T().to(device)

for name, param in model.wav2vec.named_parameters():
    if "encoder.layers" in name:
        layer_num = int(name.split("encoder.layers.")[1].split(".")[0])
        if layer_num >= 8:
            param.requires_grad = True
        else:
            param.requires_grad = False

optimizer = torch.optim.AdamW([
    {"params": model.wav2vec.parameters(), "lr": 1e-5},
    {"params": model.bilstm.parameters(), "lr": 3e-4},
    {"params": model.attention.parameters(), "lr": 3e-4},
    {"params": model.shared.parameters(), "lr": 3e-4},
    {"params": model.emotion_head.parameters(), "lr": 3e-4},
    {"params": model.drift_head.parameters(), "lr": 3e-4},
    {"params": model.confidence_head.parameters(), "lr": 3e-4},
], weight_decay=1e-4)

criterion = nn.CrossEntropyLoss()

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer,
    T_max=6
)

from sklearn.metrics import accuracy_score, recall_score, roc_auc_score
from tqdm import tqdm
import torch.nn.functional as F

# ===== TRAIN FUNCTION =====
def train_phase4(model, loader, optimizer, criterion):
    model.train()
    total_loss = 0

    all_preds = []
    all_labels = []
    all_probs = []

    for batch in tqdm(loader):

        input_values = batch["input_values"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["label"].to(device)

        optimizer.zero_grad()

        outputs = model(input_values, attention_mask)
        logits = outputs["emotion_logits"]

        loss = criterion(logits, labels)
        loss.backward()

        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()

        total_loss += loss.item()

        probs = F.softmax(logits, dim=1)[:, 1]
        preds = torch.argmax(logits, dim=1)

        all_preds.extend(preds.detach().cpu().numpy())
        all_labels.extend(labels.detach().cpu().numpy())
        all_probs.extend(probs.detach().cpu().numpy())

    acc = accuracy_score(all_labels, all_preds)
    recall_abnormal = recall_score(all_labels, all_preds, pos_label=1)
    roc = roc_auc_score(all_labels, all_probs)

    return total_loss / len(loader), acc, recall_abnormal, roc


# ===== VALIDATION FUNCTION =====
def validate_phase4(model, loader, criterion):
    model.eval()
    total_loss = 0

    all_preds = []
    all_labels = []
    all_probs = []

    with torch.no_grad():
        for batch in tqdm(loader):

            input_values = batch["input_values"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["label"].to(device)

            outputs = model(input_values, attention_mask)
            logits = outputs["emotion_logits"]

            loss = criterion(logits, labels)
            total_loss += loss.item()

            probs = F.softmax(logits, dim=1)[:, 1]
            preds = torch.argmax(logits, dim=1)

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
            all_probs.extend(probs.cpu().numpy())

    acc = accuracy_score(all_labels, all_preds)
    recall_abnormal = recall_score(all_labels, all_preds, pos_label=1)
    roc = roc_auc_score(all_labels, all_probs)

    return total_loss / len(loader), acc, recall_abnormal, roc

num_epochs = 6
best_roc = 0

for epoch in range(num_epochs):

    print(f"\nEpoch {epoch+1}/{num_epochs}")

    train_loss, train_acc, train_recall, train_roc = train_phase4(
        model, train_loader, optimizer, criterion
    )

    val_loss, val_acc, val_recall, val_roc = validate_phase4(
        model, val_loader, criterion
    )

    scheduler.step()

    print(f"Train Acc: {train_acc:.4f} | Recall: {train_recall:.4f} | ROC: {train_roc:.4f}")
    print(f"Val   Acc: {val_acc:.4f} | Recall: {val_recall:.4f} | ROC: {val_roc:.4f}")

    if val_roc > best_roc:
        best_roc = val_roc
        torch.save(model.state_dict(), "/content/drive/MyDrive/phase4_best.pt")
        print("Phase 4 best model saved!")

"""# PHASE 5 — Safety-Constrained Multi-Task Loss"""

class SafetyConstrainedMultiTaskLoss(nn.Module):
    def __init__(
        self,
        lambda_safety=2.0,
        lambda_drift=0.5,
        lambda_confidence=0.3
    ):
        super().__init__()

        self.ce = nn.CrossEntropyLoss()
        self.lambda_safety = lambda_safety
        self.lambda_drift = lambda_drift
        self.lambda_confidence = lambda_confidence

        self.mse = nn.MSELoss()
        self.bce = nn.BCELoss()

    def forward(self, outputs, targets):

        logits = outputs["emotion_logits"]
        drift_score = outputs["drift_score"].squeeze(1)
        confidence_score = outputs["confidence_score"].squeeze(1)

        # ===== Emotion CE Loss =====
        emotion_loss = self.ce(logits, targets)

        # ===== Safety False-Negative Penalty =====
        probs = torch.softmax(logits, dim=1)
        abnormal_prob = probs[:, 1]

        abnormal_mask = (targets == 1).float()

        safety_penalty = torch.mean(
            (1 - abnormal_prob) * abnormal_mask
        )

        # ===== Drift Supervision =====
        drift_target = targets.float()
        drift_loss = self.mse(drift_score, drift_target)

        # ===== Confidence Calibration =====
        preds = torch.argmax(logits, dim=1)
        correctness = (preds == targets).float()

        confidence_loss = self.bce(confidence_score, correctness)

        total_loss = (
            emotion_loss
            + self.lambda_safety * safety_penalty
            + self.lambda_drift * drift_loss
            + self.lambda_confidence * confidence_loss
        )

        return total_loss

criterion = SafetyConstrainedMultiTaskLoss(
    lambda_safety=2.0,
    lambda_drift=0.5,
    lambda_confidence=0.3
)

def train_phase5(model, loader, optimizer, criterion):
    model.train()
    total_loss = 0

    all_preds = []
    all_labels = []
    all_probs = []

    for batch in tqdm(loader):

        input_values = batch["input_values"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["label"].to(device)

        optimizer.zero_grad()

        outputs = model(input_values, attention_mask)

        loss = criterion(outputs, labels)
        loss.backward()

        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()

        total_loss += loss.item()

        logits = outputs["emotion_logits"]
        probs = torch.softmax(logits, dim=1)[:, 1]
        preds = torch.argmax(logits, dim=1)

        all_preds.extend(preds.detach().cpu().numpy())
        all_labels.extend(labels.detach().cpu().numpy())
        all_probs.extend(probs.detach().cpu().numpy())

    acc = accuracy_score(all_labels, all_preds)
    recall_abnormal = recall_score(all_labels, all_preds, pos_label=1)
    roc = roc_auc_score(all_labels, all_probs)

    return total_loss / len(loader), acc, recall_abnormal, roc

# ===== VALIDATION FUNCTION =====
def validate_phase5(model, loader, criterion):
    model.eval()
    total_loss = 0

    all_preds = []
    all_labels = []
    all_probs = []

    with torch.no_grad():
        for batch in tqdm(loader):

            input_values = batch["input_values"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["label"].to(device)

            outputs = model(input_values, attention_mask)
            logits = outputs["emotion_logits"]

            loss = criterion(logits, labels)
            total_loss += loss.item()

            probs = F.softmax(logits, dim=1)[:, 1]
            preds = torch.argmax(logits, dim=1)

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
            all_probs.extend(probs.cpu().numpy())

    acc = accuracy_score(all_labels, all_preds)
    recall_abnormal = recall_score(all_labels, all_preds, pos_label=1)
    roc = roc_auc_score(all_labels, all_probs)

    return total_loss / len(loader), acc, recall_abnormal, roc

num_epochs = 6
best_roc = 0

for epoch in range(num_epochs):

    print(f"\nEpoch {epoch+1}/{num_epochs}")

    train_loss, train_acc, train_recall, train_roc = train_phase5(
        model, train_loader, optimizer, criterion
    )

    val_loss, val_acc, val_recall, val_roc = validate_phase5(
        model, val_loader, nn.CrossEntropyLoss()
    )

    scheduler.step()

    print(f"Train Acc: {train_acc:.4f} | Recall: {train_recall:.4f} | ROC: {train_roc:.4f}")
    print(f"Val   Acc: {val_acc:.4f} | Recall: {val_recall:.4f} | ROC: {val_roc:.4f}")

    if val_roc > best_roc:
        best_roc = val_roc
        torch.save(model.state_dict(), "/content/drive/MyDrive/phase5_best.pt")
        print("Phase 5 best model saved!")

"""# Phase 5 revised plan"""

model = SDED_T().to(device)

phase3_state = torch.load("/content/drive/MyDrive/phase3_best.pt")

model_dict = model.state_dict()

# Filter only matching keys
pretrained_dict = {
    k: v for k, v in phase3_state.items()
    if k in model_dict and model_dict[k].shape == v.shape
}

model_dict.update(pretrained_dict)
model.load_state_dict(model_dict)

print("Phase 3 weights loaded into SDED-T")

for name, param in model.wav2vec.named_parameters():
    if "encoder.layers" in name:
        layer_num = int(name.split("encoder.layers.")[1].split(".")[0])
        if layer_num >= 8:
            param.requires_grad = True
        else:
            param.requires_grad = False

optimizer = torch.optim.AdamW([
    {"params": model.wav2vec.parameters(), "lr": 1e-5},
    {"params": model.bilstm.parameters(), "lr": 3e-4},
    {"params": model.attention.parameters(), "lr": 3e-4},
    {"params": model.shared.parameters(), "lr": 3e-4},
    {"params": model.emotion_head.parameters(), "lr": 3e-4},
    {"params": model.drift_head.parameters(), "lr": 3e-4},
    {"params": model.confidence_head.parameters(), "lr": 3e-4},
], weight_decay=1e-4)

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer,
    T_max=4
)

criterion = SafetyConstrainedMultiTaskLoss(
    lambda_safety=0.8,
    lambda_drift=0.3,
    lambda_confidence=0.2
)

num_epochs = 4
best_roc = 0

for epoch in range(num_epochs):

    print(f"\nEpoch {epoch+1}/{num_epochs}")

    train_loss, train_acc, train_recall, train_roc = train_phase5(
        model, train_loader, optimizer, criterion
    )

    val_loss, val_acc, val_recall, val_roc = validate_phase4(
        model, val_loader, nn.CrossEntropyLoss()
    )

    scheduler.step()

    print(f"Train Acc: {train_acc:.4f} | Recall: {train_recall:.4f} | ROC: {train_roc:.4f}")
    print(f"Val   Acc: {val_acc:.4f} | Recall: {val_recall:.4f} | ROC: {val_roc:.4f}")

    if val_roc > best_roc:
        best_roc = val_roc
        torch.save(model.state_dict(), "/content/drive/MyDrive/phase5_refined_best.pt")
        print("Refined Phase 5 best model saved!")

"""Phase 6 - Threshold optimization"""

import numpy as np
from tqdm import tqdm
import torch.nn.functional as F

model.eval()

all_labels = []
all_probs = []

with torch.no_grad():
    for batch in val_loader:

        input_values = batch["input_values"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["label"].to(device)

        outputs = model(input_values, attention_mask)
        logits = outputs["emotion_logits"]

        probs = F.softmax(logits, dim=1)[:, 1]

        all_labels.extend(labels.cpu().numpy())
        all_probs.extend(probs.cpu().numpy())

all_labels = np.array(all_labels)
all_probs = np.array(all_probs)

print("Collected validation probabilities.")

from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

def optimize_threshold_for_recall(labels, probs, target_recall=0.90):

    thresholds = np.linspace(0.1, 0.9, 200)

    best_threshold = 0.5
    best_metrics = None

    for t in thresholds:
        preds = (probs >= t).astype(int)

        recall_abnormal = recall_score(labels, preds, pos_label=1)
        precision_abnormal = precision_score(labels, preds, pos_label=1)
        acc = accuracy_score(labels, preds)
        f1 = f1_score(labels, preds, pos_label=1)

        if recall_abnormal >= target_recall:
            best_threshold = t
            best_metrics = {
                "threshold": t,
                "accuracy": acc,
                "recall_abnormal": recall_abnormal,
                "precision_abnormal": precision_abnormal,
                "f1_abnormal": f1
            }
            break

    return best_threshold, best_metrics

best_t, metrics = optimize_threshold_for_recall(
    all_labels,
    all_probs,
    target_recall=0.90
)

print("Best Threshold for Recall >= 0.90:", best_t)
print("Metrics at that threshold:", metrics)

def optimize_threshold_safety_weighted(labels, probs):

    thresholds = np.linspace(0.05, 0.9, 300)

    best_score = 0
    best_threshold = 0
    best_metrics = None

    for t in thresholds:
        preds = (probs >= t).astype(int)

        recall_abnormal = recall_score(labels, preds, pos_label=1)
        precision_abnormal = precision_score(labels, preds, pos_label=1)
        acc = accuracy_score(labels, preds)
        f1 = f1_score(labels, preds, pos_label=1)

        # Safety-weighted score
        score = 0.6 * recall_abnormal + 0.4 * f1

        if score > best_score:
            best_score = score
            best_threshold = t
            best_metrics = {
                "threshold": t,
                "accuracy": acc,
                "recall_abnormal": recall_abnormal,
                "precision_abnormal": precision_abnormal,
                "f1_abnormal": f1
            }

    return best_threshold, best_metrics

best_t, metrics = optimize_threshold_safety_weighted(
    all_labels,
    all_probs
)

print("Safety-Optimized Threshold:", best_t)
print("Metrics:", metrics)

"""# Confusion matrix"""

import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import confusion_matrix

# Default threshold = 0.5
threshold = 0.5
preds = (all_probs >= threshold).astype(int)

cm = confusion_matrix(all_labels, preds)

plt.figure()
plt.imshow(cm)
plt.title("Confusion Matrix (Threshold = 0.5)")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.xticks([0, 1])
plt.yticks([0, 1])

for i in range(2):
    for j in range(2):
        plt.text(j, i, cm[i, j], ha="center", va="center")

plt.show()

print("Confusion Matrix:\n", cm)

"""# ROC Curve Code"""

from sklearn.metrics import roc_curve, auc

fpr, tpr, thresholds = roc_curve(all_labels, all_probs)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr)
plt.plot([0, 1], [0, 1])
plt.title(f"ROC Curve (AUC = {roc_auc:.4f})")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.show()

print("ROC AUC:", roc_auc)

import shutil
shutil.copy(
    "/content/drive/MyDrive/phase5_refined_best.pt",
    "/content/drive/MyDrive/SDED_T_Final_Model.pt"
)

"""# Results for baseline,phase 3,phase4"""

state_dict = torch.load("/content/drive/MyDrive/baseline_best.pt", map_location="cpu")

print("Saved Keys:\n")
for k in list(state_dict.keys())[:20]:
    print(k)

state_dict = torch.load("/content/drive/MyDrive/baseline_best.pt", map_location="cpu")

print("\nClassifier-related keys:\n")

for k in state_dict.keys():
    if "classifier" in k:
        print(k)

class BaselineModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.wav2vec = Wav2Vec2Model.from_pretrained("facebook/wav2vec2-base")
        hidden = self.wav2vec.config.hidden_size

        self.classifier = nn.Sequential(
            nn.Linear(hidden, 256),   # classifier.0
            nn.ReLU(),                # classifier.1
            nn.Dropout(0.3),          # classifier.2
            nn.Linear(256, 2)         # classifier.3
        )

    def forward(self, input_values, attention_mask=None):
        outputs = self.wav2vec(
            input_values=input_values,
            attention_mask=attention_mask
        )

        x = outputs.last_hidden_state
        x = torch.mean(x, dim=1)

        logits = self.classifier(x)
        return logits

evaluate_model(
    "/content/drive/MyDrive/baseline_best.pt",
    BaselineModel,
    "Baseline"
)

state_dict = torch.load("/content/drive/MyDrive/phase3_best.pt", map_location="cpu")

print("\nPhase 3 Keys (classifier-related):\n")
for k in state_dict.keys():
    if "classifier" in k or "bilstm" in k or "attention" in k:
        print(k)

class Phase3Model(nn.Module):
    def __init__(self):
        super().__init__()

        self.wav2vec = Wav2Vec2Model.from_pretrained("facebook/wav2vec2-base")
        hidden = self.wav2vec.config.hidden_size

        # BiLSTM
        self.bilstm = nn.LSTM(
            input_size=hidden,
            hidden_size=256,
            num_layers=2,
            batch_first=True,
            bidirectional=True,
            dropout=0.3
        )

        # Attention
        self.attention = nn.Sequential(
            nn.Linear(512, 128),   # attention.0
            nn.Tanh(),
            nn.Linear(128, 1)      # attention.2
        )

        # Classifier
        self.classifier = nn.Sequential(
            nn.Linear(512, 256),   # classifier.0
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(256, 2)      # classifier.3
        )

    def forward(self, input_values, attention_mask=None):
        outputs = self.wav2vec(
            input_values=input_values,
            attention_mask=attention_mask
        )

        x = outputs.last_hidden_state

        # BiLSTM
        x, _ = self.bilstm(x)

        # Attention pooling
        attn_scores = self.attention(x)
        attn_weights = torch.softmax(attn_scores, dim=1)
        x = torch.sum(attn_weights * x, dim=1)

        logits = self.classifier(x)

        return logits

evaluate_model(
    "/content/drive/MyDrive/phase3_best.pt",
    Phase3Model,
    "Phase 3"
)

state_dict = torch.load("/content/drive/MyDrive/phase4_best.pt", map_location="cpu")

print("\nPhase 4 Keys:\n")
for k in state_dict.keys():
    if "bilstm" in k or "attention" in k or "shared" in k or "emotion" in k:
        print(k)

class Phase4Model(nn.Module):
    def __init__(self):
        super().__init__()

        self.wav2vec = Wav2Vec2Model.from_pretrained("facebook/wav2vec2-base")
        hidden = self.wav2vec.config.hidden_size

        # BiLSTM
        self.bilstm = nn.LSTM(
            input_size=hidden,
            hidden_size=256,
            num_layers=2,
            batch_first=True,
            bidirectional=True,
            dropout=0.3
        )

        # Attention
        self.attention = nn.Sequential(
            nn.Linear(512, 128),
            nn.Tanh(),
            nn.Linear(128, 1)
        )

        # Shared representation
        self.shared = nn.Sequential(
            nn.Linear(512, 256),
            nn.ReLU(),
            nn.Dropout(0.4)
        )

        # Emotion head
        self.emotion_head = nn.Linear(256, 2)

        # Drift head
        self.drift_head = nn.Linear(256, 1)

        # Confidence head
        self.confidence_head = nn.Sequential(
            nn.Linear(256, 64),
            nn.ReLU(),
            nn.Linear(64, 1),
            nn.Sigmoid()
        )

    def forward(self, input_values, attention_mask=None):

        outputs = self.wav2vec(
            input_values=input_values,
            attention_mask=attention_mask
        )

        x = outputs.last_hidden_state

        # BiLSTM
        x, _ = self.bilstm(x)

        # Attention pooling
        attn_scores = self.attention(x)
        attn_weights = torch.softmax(attn_scores, dim=1)
        x = torch.sum(attn_weights * x, dim=1)

        shared = self.shared(x)

        emotion_logits = self.emotion_head(shared)
        drift_score = self.drift_head(shared)
        confidence_score = self.confidence_head(shared)

        return {
            "emotion_logits": emotion_logits,
            "drift_score": drift_score,
            "confidence_score": confidence_score
        }

evaluate_model(
    "/content/drive/MyDrive/phase4_best.pt",
    Phase4Model,
    "Phase 4"
)

"""# Confusion matrix and ROC curve"""

import torch
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, roc_curve, auc

def evaluate_model(model_path, model_class, title):

    print(f"\nEvaluating {title}...\n")

    model = model_class().to(device)
    model.load_state_dict(torch.load(model_path, map_location=device))
    model.eval()

    all_probs = []
    all_labels = []

    with torch.no_grad():
        for batch in val_loader:
            input_values = batch["input_values"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["label"].to(device)

            outputs = model(input_values, attention_mask)

            # Handle dictionary output (Phase 4)
            if isinstance(outputs, dict):
                logits = outputs["emotion_logits"]
            else:
                logits = outputs

            probs = torch.softmax(logits, dim=1)[:,1]

            all_probs.extend(probs.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    all_probs = np.array(all_probs)
    all_labels = np.array(all_labels)

    # ==============================
    # Confusion Matrix
    # ==============================
    threshold = 0.5
    preds = (all_probs >= threshold).astype(int)

    cm = confusion_matrix(all_labels, preds)

    plt.figure(figsize=(6,6))
    plt.imshow(cm)
    plt.title(f"{title} - Confusion Matrix ")
    plt.xlabel("Predicted Label")
    plt.ylabel("True Label")

    for i in range(2):
        for j in range(2):
            plt.text(j, i, cm[i,j],
                     horizontalalignment="center",
                     verticalalignment="center",
                     fontsize=14)

    plt.xticks([0,1])
    plt.yticks([0,1])
    plt.colorbar()
    plt.tight_layout()
    plt.show()

    print(f"{title} Confusion Matrix:\n{cm}")

    # ==============================
    # ROC Curve
    # ==============================
    fpr, tpr, _ = roc_curve(all_labels, all_probs)
    roc_auc = auc(fpr, tpr)

    plt.figure()
    plt.plot(fpr, tpr)
    plt.plot([0,1], [0,1])
    plt.title(f"{title} ROC Curve (AUC = {roc_auc:.4f})")
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.show()

    print(f"{title} ROC AUC:", roc_auc)

evaluate_model(
    "/content/drive/MyDrive/baseline_best.pt",
    BaselineModel,
    "Transformer Baseline"
)

evaluate_model(
    "/content/drive/MyDrive/phase3_best.pt",
    Phase3Model,
    "BiLSTM + Attention"
)

evaluate_model(
    "/content/drive/MyDrive/phase4_best.pt",
    Phase4Model,
    "SDED-T (Cross-Entropy Only)"
)

state_dict = torch.load("/content/drive/MyDrive/SDED_T_Final_Model.pt", map_location="cpu")

print("Saved Keys:\n")
for k in list(state_dict.keys())[:20]:
    print(k)

print("\nTask-specific keys:\n")
for k in state_dict.keys():
    if "bilstm" in k or "attention" in k or "shared" in k or "emotion" in k or "drift" in k or "confidence" in k:
        print(k)

import torch
import torch.nn as nn
from transformers import Wav2Vec2Model


class SDED_T(nn.Module):
    def __init__(self, num_classes=2):
        super(SDED_T, self).__init__()

        # ==============================
        # 1️⃣ Pretrained Wav2Vec2 Encoder
        # ==============================
        self.wav2vec = Wav2Vec2Model.from_pretrained("facebook/wav2vec2-base")

        hidden_size = self.wav2vec.config.hidden_size

        # ==============================
        # 2️⃣ Bidirectional LSTM
        # ==============================
        self.bilstm = nn.LSTM(
            input_size=hidden_size,
            hidden_size=256,
            num_layers=2,
            batch_first=True,
            bidirectional=True,
            dropout=0.3
        )

        lstm_output_dim = 256 * 2  # because bidirectional

        # ==============================
        # 3️⃣ Attention Pooling
        # ==============================
        self.attention = nn.Sequential(
            nn.Linear(lstm_output_dim, 128),
            nn.Tanh(),
            nn.Linear(128, 1)
        )

        # ==============================
        # 4️⃣ Shared Representation Layer
        # ==============================
        self.shared = nn.Sequential(
            nn.Linear(lstm_output_dim, 256),
            nn.ReLU(),
            nn.Dropout(0.4)
        )

        # ==============================
        # 5️⃣ Emotion Classification Head
        # ==============================
        self.emotion_head = nn.Linear(256, num_classes)

        # ==============================
        # 6️⃣ Drift Head (Regression)
        # ==============================
        self.drift_head = nn.Linear(256, 1)

        # ==============================
        # 7️⃣ Confidence Head
        # ==============================
        self.confidence_head = nn.Sequential(
            nn.Linear(256, 64),
            nn.ReLU(),
            nn.Linear(64, 1),
            nn.Sigmoid()
        )

    def forward(self, input_values, attention_mask=None):

        # ==============================
        # Wav2Vec2 Feature Extraction
        # ==============================
        outputs = self.wav2vec(
            input_values=input_values,
            attention_mask=attention_mask
        )

        x = outputs.last_hidden_state  # (batch, time, hidden)

        # ==============================
        # BiLSTM Temporal Modeling
        # ==============================
        x, _ = self.bilstm(x)

        # ==============================
        # Attention Pooling
        # ==============================
        attn_scores = self.attention(x)
        attn_weights = torch.softmax(attn_scores, dim=1)
        x = torch.sum(attn_weights * x, dim=1)

        # ==============================
        # Shared Representation
        # ==============================
        shared = self.shared(x)

        # ==============================
        # Multi-Task Outputs
        # ==============================
        emotion_logits = self.emotion_head(shared)
        drift_score = self.drift_head(shared)
        confidence_score = self.confidence_head(shared)

        return {
            "emotion_logits": emotion_logits,
            "drift_score": drift_score,
            "confidence_score": confidence_score
        }

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = SDED_T().to(device)

model.load_state_dict(
    torch.load("/content/drive/MyDrive/SDED_T_Final_Model.pt", map_location=device)
)
model.eval()

import torch
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, roc_curve, auc

def evaluate_proposed_model(model, val_loader, device, threshold=0.5):

    model.eval()
    all_probs = []
    all_labels = []

    with torch.no_grad():
        for batch in val_loader:
            input_values = batch["input_values"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["label"].to(device)

            outputs = model(input_values, attention_mask)
            logits = outputs["emotion_logits"]

            probs = torch.softmax(logits, dim=1)[:, 1]

            all_probs.extend(probs.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    all_probs = np.array(all_probs)
    all_labels = np.array(all_labels)

    # =========================
    # Confusion Matrix
    # =========================
    preds = (all_probs >= threshold).astype(int)
    cm = confusion_matrix(all_labels, preds)

    plt.figure(figsize=(6,6))
    plt.imshow(cm)
    plt.title("SDED-T + SCMTL (Proposed) - Confusion Matrix")
    plt.xlabel("Predicted Label")
    plt.ylabel("True Label")

    for i in range(2):
        for j in range(2):
            plt.text(j, i, cm[i,j],
                     horizontalalignment="center",
                     verticalalignment="center",
                     fontsize=14)

    plt.xticks([0,1])
    plt.yticks([0,1])
    plt.colorbar()
    plt.tight_layout()
    plt.show()

    print("Confusion Matrix:\n", cm)

    # =========================
    # ROC Curve
    # =========================
    fpr, tpr, _ = roc_curve(all_labels, all_probs)
    roc_auc = auc(fpr, tpr)

    plt.figure()
    plt.plot(fpr, tpr)
    plt.plot([0,1], [0,1])
    plt.title(f"SDED-T + SCMTL (Proposed) ROC Curve (AUC = {roc_auc:.4f})")
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.show()

    print("ROC-AUC:", roc_auc)

evaluate_proposed_model(model, val_loader, device)